name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
  workflow_run:
    workflows: ["Synchronize data"]
    types:
      - completed
      
# Allow this job to clone the repo and create a page deployment
permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Creating artifact placeholder file
        run: echo "this is a placeholder file" > artifact.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.txt
          
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Prague"

      - name: Cache
        run: make cache

      - name: Test
        run: make test

      - name: Build bundle
        run: make build

      - name: Add custom domain
        run: "touch dist/CNAME && echo \"data.web3privacy.info\" >> dist/CNAME"
          
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
